### ISSUE TITLE
Verify windows implementation

### ISSUE THREAD

**Issue by nicokoch** [nicokoch/reflink#1]
Is only compile-tested at the moment

**Comment by jerickmsft** [comment]
As a head's up, FSCTL_DUPLICATE_EXTENTS_TO_FILE only works on ReFS [which is only available on Windows Server 2016+](https://docs.microsoft.com/en-us/windows/desktop/FileIO/block-cloning).  To makes things worse, ReFS volumes are not bootable. Therefore, this will not work on any Windows boot volume.

Running the example on 99.999% of Windows volumes will result in this:
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: Other, message: "Incorrect function." }', libcore\result.rs:945:5```

Sorry to be the bearer of bad news!

**Comment by nicokoch** [comment]
> Running the example on 99.999% of Windows volumes will result in this:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: Other, message: "Incorrect function." }', libcore\result.rs:945:5

This is known and expected.
If certain file systems do not support the functionality, we can't to anything about it.

Maybe in the future, some Windows client versions will be supported.
